### ISSUE TITLE
Support for Phoenix.HTML.Form datetime_select Function

### ISSUE THREAD

**Issue by kexoth** [Paradem/phoenix_timex#2]
I'm quite new to Phoenix, but from your description I understood that the purpose of this library is to make Timex datetimes to be passed & processed by Phoenix form builders/helpers. 

That's why I implemented this module according to your documentation, but cannot seem to make it work.

Can you give me any suggestions/explanations?

Thanks!

**Comment by kiliancs** [comment]
@kexoth Sorry if its purpose is not clear, but really Phoenix Timex simply allows you to write Timex dates and times directly without formatting them explicitly.

You may use https://github.com/bitwalker/timex_ecto to integrate Timex with Ecto. With it you can use Timex in Ecto columns and use them in forms normally.

**Comment by kexoth** [comment]
@kiliancs actually I use timex_ecto for that purpose, but what I thought is that this library makes builders for select_date, select_time & select_datetime for Timex object as for the regular ones.

**Comment by kiliancs** [comment]
@kexoth sorry for the very delayed reply. Phoenix Timex won't create those builders.
